subroutine allocate_memory

    use set_parameter
    
    implicit none
    
    !配列のサイズの指定
    allocate (node(ncount, dim))
    allocate (element(ecount, ipn))
    
    allocate (gauss(ipn, dim))
    allocate (polar(ipn, dim))
    
    allocate (x(ncount*dim, 1))
    allocate (penalty_number(pair, 2))
    
    allocate (microS_vm_e(ecount))
    allocate (microS_vm_g(ecount, ipn))
    allocate (microS_vm_n(ncount))
    
    allocate (young(ecount))
    allocate (poisson(ecount))
    allocate (material_number(ecount))
    
    allocate (Dmatrix(ecount, dir, dir))
    allocate (Smatrix(dim, dir, dir))
    allocate (invSmatrix(dim, dir, dir))
    allocate (Bmatrix(ecount, ipn, dir, scount*dim))
    allocate (Kmatrix(ncount*dim, ncount*dim))
    allocate (Kmat_LU(ncount*dim, ncount*dim))
    allocate (eKmatrix(ecount, scount*dim, scount*dim))
    allocate (eKmat_cc(ecount, ipn*dim, ipn*dim))
    allocate (eKmat_cn(ecount, ipn*dim, dim*dim))
    allocate (eKmat_nc(ecount, dim*dim, ipn*dim))
    allocate (eKmat_nn(ecount, dim*dim, dim*dim))
    allocate (inveKmat_nn(ecount, dim*dim, dim*dim))
    allocate (eKcn_inveKnn(ecount, ipn*dim, dim*dim))
    allocate (eKcn_inveKnn_eKnc(ecount, ipn*dim, ipn*dim))
    allocate (Hmatrix(ecount, ipn, dim, scount))
    allocate (Jmatrix(ecount, scount, dim, dim))
    allocate (invJmatrix(ecount, scount, dim, dim))
    allocate (det_J(ecount, ipn))
    allocate (cartesian(ecount, ipn, dim, scount))
    allocate (tBmatDmat(ecount, ipn, scount*dim, dir))
    allocate (tBmatDmatBmat(ecount, ipn, scount*dim, scount*dim))
    
    allocate (eFmatrix(ecount, scount*dim, dir))
    allocate (eFmat_c(ecount, ipn*dim, dir))
    allocate (eFmat_n(ecount, dim*dim, dir))
    allocate (eKcn_inveKnn_eFn(ecount, ipn*dim, dir))
    allocate (Fmatrix(ncount*dim, dir))
    allocate (Xmatrix(ncount*dim, dir))
    allocate (eXmat_c(ecount, ipn*dim, dir))    
    allocate (eKnc_eXc(ecount, dim*dim, dir))  
    allocate (eXmat_n(ecount, dim*dim, dir)) 
    allocate (eXmatrix(ecount, scount*dim, dir))
           
    allocate (BmatXmat(ecount, ipn, dir, dir))
    allocate (DmatBmatXmat(ecount, ipn, dir, dir))
    allocate (eAmatrix(ecount, ipn+dim, dir, dir))
    allocate (Amatrix(dir, dir))
    allocate (invAmatrix(dir, dir))
    
    allocate (macroS(dir))
    allocate (macroE(dir))
    allocate (microS_gauss(ecount, ipn+dim, dir))
    allocate (microS_element(ecount, dir))
    allocate (microS_node(ncount, dir))
    allocate (macroE_tensor(dim, dim))
    allocate (u_sharp(ncount, dim))
    allocate (microU(ncount, dim))
    allocate (n_counter(ncount))
    
        allocate (hf(ecount,scount))
    allocate (S_dev(ecount, scount, dir))
    allocate (S_equ(ecount,scount))
    allocate (Beta(ecount, ipn+dim, dir))
    allocate (Ep_acc(ecount, ipn+dim))
    allocate (eGvector(ecount, scount*dim))
    allocate (eGvec_c(ecount, ipn*dim))
    allocate (eGvec_n(ecount, dim*dim))
    allocate (eKcn_inveKnn_eGn(ecount, ipn*dim))
    allocate (Gvector(ncount*dim))
    allocate (Pvector(ncount*dim))
    allocate (ePvec_c(ecount, ipn*dim))
    allocate (eKnc_ePc(ecount, dim*dim))
    allocate (ePvec_n(ecount, dim*dim))
    allocate (ePvector(ecount, scount*dim))
    allocate (DmatBeta(ecount, ipn, dir))
    allocate (DmatBmat(ecount, ipn, dir, scount*dim))
    allocate (eRvector(ecount, scount, dir))
    allocate (Rvector(dir))
    allocate (macroS_velocity(dir))
    allocate (macroE_velocity(dir))
    allocate (microS_velocity(ecount, ipn+dim, dir))
    allocate (u_sharp_velocity(ncount, dim))
    allocate (node_after(ncount, dim))
allocate( Ep_el(ecount))
end subroutine