        !COMPILER-GENERATED INTERFACE MODULE: Wed Oct 29 15:24:57 2025
        MODULE ALLOCATE_MEMORY_mod
          INTERFACE 
            SUBROUTINE ALLOCATE_MEMORY
            END SUBROUTINE ALLOCATE_MEMORY
          END INTERFACE 
        END MODULE ALLOCATE_MEMORY_mod
