        !COMPILER-GENERATED INTERFACE MODULE: Wed Oct 29 15:24:58 2025
        MODULE BOUNDARY_CONDITION_mod
          INTERFACE 
            SUBROUTINE BOUNDARY_CONDITION
            END SUBROUTINE BOUNDARY_CONDITION
          END INTERFACE 
        END MODULE BOUNDARY_CONDITION_mod
