        !COMPILER-GENERATED INTERFACE MODULE: Thu Oct 30 23:17:45 2025
        MODULE INPUT_mod
          INTERFACE 
            SUBROUTINE INPUT
            END SUBROUTINE INPUT
          END INTERFACE 
        END MODULE INPUT_mod
