        !COMPILER-GENERATED INTERFACE MODULE: Thu Oct 30 23:14:57 2025
        MODULE MAKE_BETA_mod
          INTERFACE 
            SUBROUTINE MAKE_BETA
            END SUBROUTINE MAKE_BETA
          END INTERFACE 
        END MODULE MAKE_BETA_mod
