        !COMPILER-GENERATED INTERFACE MODULE: Wed Oct 29 15:24:55 2025
        MODULE MAKE_KMATRIX_mod
          INTERFACE 
            SUBROUTINE MAKE_KMATRIX
            END SUBROUTINE MAKE_KMATRIX
          END INTERFACE 
        END MODULE MAKE_KMATRIX_mod
