        !COMPILER-GENERATED INTERFACE MODULE: Wed Oct 29 15:24:56 2025
        MODULE MAKE_GVECTOR_mod
          INTERFACE 
            SUBROUTINE MAKE_GVECTOR
            END SUBROUTINE MAKE_GVECTOR
          END INTERFACE 
        END MODULE MAKE_GVECTOR_mod
