        !COMPILER-GENERATED INTERFACE MODULE: Wed Oct 29 15:24:59 2025
        MODULE MAKE_INVJMATRIX_mod
          INTERFACE 
            SUBROUTINE MAKE_INVJMATRIX
            END SUBROUTINE MAKE_INVJMATRIX
          END INTERFACE 
        END MODULE MAKE_INVJMATRIX_mod
