        !COMPILER-GENERATED INTERFACE MODULE: Wed Oct 29 15:24:56 2025
        MODULE MAKE_EFMATRIX_mod
          INTERFACE 
            SUBROUTINE MAKE_EFMATRIX
            END SUBROUTINE MAKE_EFMATRIX
          END INTERFACE 
        END MODULE MAKE_EFMATRIX_mod
