        !COMPILER-GENERATED INTERFACE MODULE: Wed Oct 29 15:24:59 2025
        MODULE MAKE_FMATRIX_mod
          INTERFACE 
            SUBROUTINE MAKE_FMATRIX
            END SUBROUTINE MAKE_FMATRIX
          END INTERFACE 
        END MODULE MAKE_FMATRIX_mod
