        !COMPILER-GENERATED INTERFACE MODULE: Wed Oct 29 15:24:57 2025
        MODULE MAKE_HMATRIX_mod
          INTERFACE 
            SUBROUTINE MAKE_HMATRIX
            END SUBROUTINE MAKE_HMATRIX
          END INTERFACE 
        END MODULE MAKE_HMATRIX_mod
