        !COMPILER-GENERATED INTERFACE MODULE: Wed Oct 29 15:24:56 2025
        MODULE MAKE_BMATRIX_mod
          INTERFACE 
            SUBROUTINE MAKE_BMATRIX
            END SUBROUTINE MAKE_BMATRIX
          END INTERFACE 
        END MODULE MAKE_BMATRIX_mod
