        !COMPILER-GENERATED INTERFACE MODULE: Wed Oct 29 15:24:58 2025
        MODULE MAKE_EKMATRIX_mod
          INTERFACE 
            SUBROUTINE MAKE_EKMATRIX
            END SUBROUTINE MAKE_EKMATRIX
          END INTERFACE 
        END MODULE MAKE_EKMATRIX_mod
