        !COMPILER-GENERATED INTERFACE MODULE: Wed Oct 29 15:24:58 2025
        MODULE MAKE_AMATRIX_mod
          INTERFACE 
            SUBROUTINE MAKE_AMATRIX
            END SUBROUTINE MAKE_AMATRIX
          END INTERFACE 
        END MODULE MAKE_AMATRIX_mod
