        !COMPILER-GENERATED INTERFACE MODULE: Wed Oct 29 15:24:58 2025
        MODULE MAKE_DMATRIX_mod
          INTERFACE 
            SUBROUTINE MAKE_DMATRIX
            END SUBROUTINE MAKE_DMATRIX
          END INTERFACE 
        END MODULE MAKE_DMATRIX_mod
