        !COMPILER-GENERATED INTERFACE MODULE: Wed Oct 29 15:24:57 2025
        MODULE MAKE_SMATRIX_mod
          INTERFACE 
            SUBROUTINE MAKE_SMATRIX
            END SUBROUTINE MAKE_SMATRIX
          END INTERFACE 
        END MODULE MAKE_SMATRIX_mod
