        !COMPILER-GENERATED INTERFACE MODULE: Wed Oct 29 15:24:58 2025
        MODULE MAKE_XMATRIX_mod
          INTERFACE 
            SUBROUTINE MAKE_XMATRIX
            END SUBROUTINE MAKE_XMATRIX
          END INTERFACE 
        END MODULE MAKE_XMATRIX_mod
