        !COMPILER-GENERATED INTERFACE MODULE: Wed Oct 29 15:24:55 2025
        MODULE MAKE_EAMATRIX_mod
          INTERFACE 
            SUBROUTINE MAKE_EAMATRIX
            END SUBROUTINE MAKE_EAMATRIX
          END INTERFACE 
        END MODULE MAKE_EAMATRIX_mod
