        !COMPILER-GENERATED INTERFACE MODULE: Wed Oct 29 15:24:59 2025
        MODULE MAKE_PVECTOR_mod
          INTERFACE 
            SUBROUTINE MAKE_PVECTOR
            END SUBROUTINE MAKE_PVECTOR
          END INTERFACE 
        END MODULE MAKE_PVECTOR_mod
