        !COMPILER-GENERATED INTERFACE MODULE: Wed Oct 29 15:24:56 2025
        MODULE OUTPUT_PARAVIEW_mod
          INTERFACE 
            SUBROUTINE OUTPUT_PARAVIEW
            END SUBROUTINE OUTPUT_PARAVIEW
          END INTERFACE 
        END MODULE OUTPUT_PARAVIEW_mod
