        !COMPILER-GENERATED INTERFACE MODULE: Wed Oct 29 15:24:59 2025
        MODULE SET_COORDINATES_mod
          INTERFACE 
            SUBROUTINE SET_COORDINATES
            END SUBROUTINE SET_COORDINATES
          END INTERFACE 
        END MODULE SET_COORDINATES_mod
