        !COMPILER-GENERATED INTERFACE MODULE: Wed Oct 29 15:24:57 2025
        MODULE SOLVE_EQUATION_mod
          INTERFACE 
            SUBROUTINE SOLVE_EQUATION(A,B,SOLUTION,M,N,NRHS)
              INTEGER(KIND=4), INTENT(IN) :: NRHS
              INTEGER(KIND=4), INTENT(IN) :: N
              INTEGER(KIND=4), INTENT(IN) :: M
              REAL(KIND=8), INTENT(IN) :: A(M,N)
              REAL(KIND=8), INTENT(IN) :: B(M,NRHS)
              REAL(KIND=8), INTENT(INOUT) :: SOLUTION(M,NRHS)
            END SUBROUTINE SOLVE_EQUATION
          END INTERFACE 
        END MODULE SOLVE_EQUATION_mod
