        !COMPILER-GENERATED INTERFACE MODULE: Wed Oct 29 15:24:59 2025
        MODULE SOLVE_MICRO_mod
          INTERFACE 
            SUBROUTINE SOLVE_MICRO
            END SUBROUTINE SOLVE_MICRO
          END INTERFACE 
        END MODULE SOLVE_MICRO_mod
