        !COMPILER-GENERATED INTERFACE MODULE: Wed Oct 29 15:24:56 2025
        MODULE SOLVE_MACRO_mod
          INTERFACE 
            SUBROUTINE SOLVE_MACRO
            END SUBROUTINE SOLVE_MACRO
          END INTERFACE 
        END MODULE SOLVE_MACRO_mod
