        !COMPILER-GENERATED INTERFACE MODULE: Wed Oct 29 15:24:55 2025
        MODULE TIME_DEPENDENT_mod
          INTERFACE 
            SUBROUTINE TIME_DEPENDENT
            END SUBROUTINE TIME_DEPENDENT
          END INTERFACE 
        END MODULE TIME_DEPENDENT_mod
